/* eslint-disable react-hooks/set-state-in-effect */
import { useEffect, useState } from "react";
import axios from "axios";
import "./Admin.css";
import AdminLayout from "../../components/AdminLayout";
import { EmptyState, LoadingState, StatusBadge } from "../../components/Ui";

export default function Categories() {
  const [categories, setCategories] = useState([]), [name, setName] = useState(""), [editingId, setEditingId] = useState(null), [filter, setFilter] = useState("active"), [saving, setSaving] = useState(false), [loading, setLoading] = useState(true), [error, setError] = useState("");
  const headers = () => ({ Authorization: `Bearer ${localStorage.getItem("adminToken")}` });
  const getCategories = async (status = filter) => { setLoading(true); try { const res = await axios.get(`http://localhost:2411/api/categories/?status=${status}`, { headers: headers() }); setCategories(res.data.categories || []); } catch { setError("Unable to load categories."); } finally { setLoading(false); } };
  useEffect(() => { getCategories("active"); }, []);
  const save = async e => { e.preventDefault(); if (!name.trim()) return setError("Category name is required."); setSaving(true); try { if (editingId) await axios.put(`http://localhost:2411/api/categories/${editingId}`, { name }, { headers: headers() }); else await axios.post("http://localhost:2411/api/categories/", { name }, { headers: headers() }); setName(""); setEditingId(null); setError(""); getCategories(); } catch (e) { setError(e.response?.data?.message || "Failed to save category."); } finally { setSaving(false); } };
  const status = async (id, current) => { const action = current === "active" ? "deactivate" : "activate"; if (!window.confirm(`Are you sure you want to ${action} this category?`)) return; try { await axios.put(`http://localhost:2411/api/categories/${id}/status`, {}, { headers: headers() }); getCategories(); } catch (e) { alert(e.response?.data?.message || "Failed to update category status"); } };
  return <AdminLayout title="Categories"><div className="admin-form-card mb-4"><h2 className="section-title mb-3">{editingId ? "Edit category" : "Add category"}</h2><form onSubmit={save}><div className="row g-3"><div className="col-12 col-md-8"><label className="form-label" htmlFor="categoryName">Category name</label><input id="categoryName" className="form-control" value={name} onChange={e => setName(e.target.value)} placeholder="e.g. Travel" /></div><div className="col-12 col-md-4 d-flex gap-2 align-self-end"><button className="btn btn-primary flex-grow-1" disabled={saving}>{saving ? "Saving..." : editingId ? "Save Changes" : "Add Category"}</button>{editingId && <button className="btn btn-outline-secondary" type="button" onClick={() => { setEditingId(null); setName(""); }}>Cancel</button>}</div></div></form></div>{error && <div className="alert alert-danger">{error}</div>}<section className="section-card"><div className="d-flex flex-wrap gap-2 justify-content-between align-items-center mb-3"><h2 className="section-title">Category list</h2><div className="filter-pills btn-group btn-group-sm">{["active", "inactive", "all"].map(s => <button key={s} className={`btn ${filter === s ? "btn-primary" : "btn-outline-secondary"}`} onClick={() => { setFilter(s); getCategories(s); }}>{s[0].toUpperCase() + s.slice(1)}</button>)}</div></div>{loading ? <LoadingState label="Loading categories..." /> : categories.length ? <div className="table-responsive"><table className="table table-hover data-table"><thead><tr><th>Category</th><th>Status</th><th>Actions</th></tr></thead><tbody>{categories.map(c => <tr key={c._id} className={c.status !== "active" ? "table-light text-secondary" : ""}><td className="fw-medium">{c.name}</td><td><StatusBadge status={c.status} /></td><td><div className="d-flex flex-wrap gap-2"><button className="btn btn-sm btn-outline-secondary" onClick={() => { setEditingId(c._id); setName(c.name); }}>Edit</button><button className={`btn btn-sm ${c.status === "active" ? "btn-outline-danger" : "btn-outline-success"}`} onClick={() => status(c._id, c.status)}>{c.status === "active" ? "Deactivate" : "Activate"}</button></div></td></tr>)}</tbody></table></div> : <EmptyState label="No categories found." />}</section></AdminLayout>;
}
