/* eslint-disable react-hooks/set-state-in-effect */
import { useEffect, useState } from "react";
import "./Admin.css";
import AdminLayout from "../../components/AdminLayout";
import { EmptyState, LoadingState, StatusBadge, formatDate } from "../../components/Ui";
import api from "../../services/api";

export default function Employees() {
  const [employees, setEmployees] = useState([]), [data, setData] = useState({ name: "", employeeCode: "" }), [saving, setSaving] = useState(false), [loading, setLoading] = useState(true), [filter, setFilter] = useState("active"), [error, setError] = useState("");
  const headers = () => ({ Authorization: `Bearer ${localStorage.getItem("adminToken")}` });
  const getEmployees = async (status = filter) => { setLoading(true); try { const res = await api.get(`/employees/?status=${status}`, { headers: headers() }); setEmployees(res.data.employees || []); setError(""); } catch { setError("Unable to load employees."); } finally { setLoading(false); } };
  useEffect(() => { getEmployees("active"); }, []);
  const submit = async e => { e.preventDefault(); if (!data.name || !data.employeeCode) return setError("Name and employee code are required."); setSaving(true); try { const res = await api.post("/employees/?status=active", data, { headers: headers() }); alert(`Employee created successfully.\nPIN: ${res.data.generatedPin}`); setData({ name: "", employeeCode: "" }); getEmployees(); } catch (e) { setError(e.response?.data?.message || "Failed to create employee."); } finally { setSaving(false); } };
  const changePin = async id => { if (!window.confirm("Generate a new PIN for this employee?")) return; try { const res = await api.put(`/employees/${id}/pin`, {}, { headers: headers() }); alert(`New Employee PIN: ${res.data.generatedPin}`); } catch (e) { alert(e.response?.data?.message || "Failed to change PIN"); } };
  const changeStatus = async (id, status) => { const action = status === "active" ? "deactivate" : "activate"; if (!window.confirm(`Are you sure you want to ${action} this employee?`)) return; try { await api.put(`/employees/${id}/status`, {}, { headers: headers() }); getEmployees(); } catch (e) { alert(e.response?.data?.message || "Failed to update status"); } };
  return <AdminLayout title="Employees"><div className="admin-form-card mb-4"><h2 className="section-title mb-3">Add employee</h2><form onSubmit={submit}><div className="row g-3"><div className="col-12 col-md-5"><label className="form-label" htmlFor="employeeName">Name</label><input id="employeeName" className="form-control" name="name" value={data.name} onChange={e => setData({ ...data, name: e.target.value })} placeholder="Employee name" /></div><div className="col-12 col-md-5"><label className="form-label" htmlFor="employeeCode">Employee code</label><input id="employeeCode" className="form-control" name="employeeCode" value={data.employeeCode} onChange={e => setData({ ...data, employeeCode: e.target.value })} placeholder="e.g. EMP-001" /></div><div className="col-12 col-md-2 d-grid align-self-end"><button className="btn btn-primary" disabled={saving}>{saving ? "Creating..." : "Add Employee"}</button></div></div></form></div>{error && <div className="alert alert-danger">{error}</div>}<section className="section-card"><div className="d-flex flex-wrap gap-2 justify-content-between align-items-center mb-3"><h2 className="section-title">Employee list</h2><div className="filter-pills btn-group btn-group-sm">{["active", "inactive", "all"].map(s => <button key={s} className={`btn ${filter === s ? "btn-primary" : "btn-outline-secondary"}`} onClick={() => { setFilter(s); getEmployees(s); }}>{s[0].toUpperCase() + s.slice(1)}</button>)}</div></div>{loading ? <LoadingState label="Loading employees..." /> : employees.length ? <div className="table-responsive"><table className="table table-hover data-table"><thead><tr><th>Name</th><th>Employee code</th><th>Status</th><th>Created</th><th>Actions</th></tr></thead><tbody>{employees.map(e => <tr className={e.status !== "active" ? "table-light text-secondary" : ""} key={e._id}><td className="fw-medium">{e.name}</td><td>{e.employeeCode}</td><td><StatusBadge status={e.status} /></td><td>{formatDate(e.createdAt)}</td><td><div className="d-flex flex-wrap gap-2"><button className="btn btn-sm btn-outline-secondary" onClick={() => changePin(e._id)}>Manage PIN</button><button className={`btn btn-sm ${e.status === "active" ? "btn-outline-danger" : "btn-outline-success"}`} onClick={() => changeStatus(e._id, e.status)}>{e.status === "active" ? "Deactivate" : "Activate"}</button></div></td></tr>)}</tbody></table></div> : <EmptyState label="No employees found." />}</section></AdminLayout>;
}
